# Site settings
title: Code better than I grammar
header-img: img/home-bg.png
email: mr.omarmason@gmail.com
copyright_name: PhreeMason
description: > # this means to ignore newlines until "baseurl:"
  Heh
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  PhreeMason
learn_profile: PhreeMason
email_username: mr.omarmason@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
